_crash_add:
    pattern:  /crash/add
    defaults: { _controller: MLabsAcraServerBundle:Crash:add }
    methods:  [POST]

_crash_details:
    pattern:  /crash/details/{id}
    defaults: { _controller: MLabsAcraServerBundle:Issue:crashDetails }
    methods:  [GET]
    requirements:
        id: \d+

_issue_details:
    pattern:  /issue/details/{issueId}
    defaults: { _controller: MLabsAcraServerBundle:Issue:issueDetails, issueId: a }
    methods:  [GET]
    requirements:
        issueId: "[0-9a-fA-F]{32}"

_app_dashboard:
    pattern:  /application/{packageName}
    defaults: { _controller: MLabsAcraServerBundle:Issue:appDashboard, packageName: com.example.myapp }
    methods:  [GET]
    requirements:
        packageName: "[0-9a-zA-Z\.]+"

_main_dashboard:
    pattern:  /dashboard
    defaults: { _controller: MLabsAcraServerBundle:Issue:dashboard }
    methods:  [GET]


#_crash_test_data:
#    pattern:  /crash/generate_data
#    defaults: { _controller: MLabsAcraServerBundle:Crash:generateTestData }
#    methods:  [GET]
