_crash_add:
    pattern:  /crash/add
    defaults: { _controller: MLabsAcraServerBundle:Crash:add }
    methods:  [POST]

_crash_list:
    pattern:  /crash/list
    defaults: { _controller: MLabsAcraServerBundle:Crash:list }
    methods:  [GET]

_crash_details:
    pattern:  /crash/details/{id}
    defaults: { _controller: MLabsAcraServerBundle:Crash:details }
    methods:  [GET]
    requirements:
        id: \d+

_issue_details:
    pattern:  /issue/{id}
    defaults: { _controller: MLabsAcraServerBundle:Issue:details }
    methods:  [GET]
    requirements:
        id: "[0-9a-fA-F]{32}"

_app_dashboard:
    pattern:  /app/{packageName}
    defaults: { _controller: MLabsAcraServerBundle:Issue:appDashboard }
    methods:  [GET]
    requirements:
        id: "[0-9a-fA-F\.]+"

_main_dashboard:
    pattern:  /
    defaults: { _controller: MLabsAcraServerBundle:Issue:dashboard }
    methods:  [GET]


#_crash_test_data:
#    pattern:  /crash/generate_data
#    defaults: { _controller: MLabsAcraServerBundle:Crash:generateTestData }
#    methods:  [GET]
