_crash_add:
    pattern:  /crash/add
    defaults: { _controller: MLabsAcraServerBundle:Crash:add }
    methods:  [POST]

_crash_details:
    pattern:  /crash/details/{id}
    defaults: { _controller: MLabsAcraServerBundle:Issue:crashDetails }
    methods:  [GET]
    requirements:
        id: \d+

_issue_details:
    pattern:  /issue/details/{id}
    defaults: { _controller: MLabsAcraServerBundle:Issue:issueDetails }
    methods:  [GET]
    requirements:
        id: "[0-9a-fA-F]{32}"

_crash_list:
    pattern:  /crash/list/{issueId}
    defaults: { _controller: MLabsAcraServerBundle:Issue:issueCrashes }
    methods:  [GET]
    requirements:
        issueId: "[0-9a-fA-F]{32}"

_issue_list:
    pattern:  /issue/list/{packageName}
    defaults: { _controller: MLabsAcraServerBundle:Crash:appIssues }
    methods:  [GET]
    requirements:
        packageName: "[0-9a-zA-Z\.]+"

_app_dashboard:
    pattern:  /app/{packageName}
    defaults: { _controller: MLabsAcraServerBundle:Issue:appDashboard }
    methods:  [GET]
    requirements:
        packageName: "[0-9a-zA-Z\.]+"

_main_dashboard:
    pattern:  /
    defaults: { _controller: MLabsAcraServerBundle:Issue:dashboard }
    methods:  [GET]


#_crash_test_data:
#    pattern:  /crash/generate_data
#    defaults: { _controller: MLabsAcraServerBundle:Crash:generateTestData }
#    methods:  [GET]
