parameters:
#    m_labs_as_web_service.example.class: MarvinLabs\AcraServerBundle\Example

services:
#    m_labs_as_web_service.example:
#        class: %m_labs_as_web_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
