parameters:
    m_labs_acra_server.table_prefix: as_

services:
    m_labs_acra_server.table_prefix_subscriber:
        class: MarvinLabs\AcraServerBundle\Subscriber\TablePrefixSubscriber
        arguments: [%m_labs_acra_server.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }

    m_labs_acra_server.before_controller_action_listener:
        class: MarvinLabs\AcraServerBundle\EventListener\BeforeControllerListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
