parameters:
    m_labs_acra_server.table_prefix: as_

services:
    m_labs_acra_server.table_prefix_subscriber:
        class: MarvinLabs\AcraServerBundle\Subscriber\TablePrefixSubscriber
        arguments: [%m_labs_acra_server.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
